language: bash

services: docker

env:
  global:
    - secure: "h5bhVneZIhdnNHTp2Ik6WHaxrmP3oTX9Mhlo1rMVvAtKGVt/HqINN2gXracAVwg+C1St//yt/1GcTehcyL+Bzwp8JIAgDKfYtNZbbkUWt1hfdXpCmO8IdMzBpXHkTg4pJGkacqSeQRyrIa1KKDBxGs0uS0g/F17NIuPYHgIGBaFCAjKlfm++VejBzuc8XnC8OLk4mrOEwyHdd6iWd9gDoXbhfZzpVOskZy13bVZ3zUm4bX2Rx93LtTKJUAJ/wjjEY5YPuEFLmtL4ZbQkcFy5LJGh+qBwcVIKTaJhmoUTiv7k1L8GUKqByRUMX9tdqK06JBML30RKvsLUuZAL9fIMxk7zs3WWTqVa6PQP8Ifjv/M3WGP16f5JQJGnLva6f6y1cVQEGV642qQZkK1D1APSfikulpk9zXI3MP6Ujxj8rT8L1G7tyrmGbdaiTSbQuK2SCydQwycPN5ki5EHJL5GQNDsH9aE6swUMpuLk5W7RbhAPWr5r+MEKRmlsXXE7SLgXqLMNH9pinICBo+ltaW2aWjuuVd2DsnwSYh8HxRBBm0gCeSSORlUm29xVGEy1VtHT9tdhWNITwTULC/gmeK4nOEQdz0Z4Pp6QNVrDuRFpvNqniOV5KKCr2yDBEqXIIcoBArrcXT7QMxQ7ivq5rnYW9pmnWyzv+XL61zIVYXJhQ6E="
    - secure: "prnPicsZE4X7ZyN+ChZa9dVOwUOgGi+bE2ZqYZOle3ybe7C8DGgmms2wXO0NbXHIYFU0V7NibfUk7bLKRMtViJfOxPfHdIdWVINDEHenTc/XoO0Yr5l0pij+A/VG68U2OZHN5XCR23Hv46Gpa7qjYgPV867yo6O3gm42okrLa6b86PlKL+oiiWMczFtWbbq59752WxHzVJpEGKYJSVu3110pVZ+g4rMwDtm9ORNamlBd/x+IQuX2cI3h1AxFDuajGNHnFHSqgAxX/SI2NFqP17n4Y7HXDZxSQmNwdyR0SFgYiUP8xeduUEC5eocR8IrwuLgHsDOJdq6xmi7vtEgNlYluA/nxwCds9x4SQAfUNq5GzPzCKJgKMsfI9ZsWD2iwgOpA2dOi9QfCWBfn2d23rle0H1F7YEprcvNb+BDWafL0hZ9bZdPfrvL1AwFsD0QzB2y+LuLAjjpN5bNrkqq7/iIYZeRpjMvme1l/QhrRLwOfq9wffd8D1/sPZMrLQYNIXUs9nOTcw97zu+aiVj4/eCUE3/I0z654hsZZOXUUNHf/6C6kRjlkRqvCliyEhTQd/yP+JdPHNAwmHAKPxxxkaCb1oAPb+xyiW3yKjXvF4/0HeP7NiRWLWPq+Lvy4+NfHjFXY+ddF8CzAasBpTGLDqhs+Vgf4Rv0PkRfQTwpb5ZM="
  matrix:
    - VERSION=7.1
    - VERSION=latest VERSION_ALIAS=7.1

before_script:
  - if [[ "$VERSION" != "latest" ]]; then cd "src/$VERSION"; fi
  - if [[ "$VERSION" == "latest" ]]; then cd "src/$VERSION_ALIAS"; fi
  - IMAGE_NAME="chesszebra/php:${VERSION}"

script:
  - docker build -t "$IMAGE_NAME" .

after_success:
  - docker login --username $DOCKER_USER --password $DOCKER_PASS
  - docker push $IMAGE_NAME

after_script:
  - docker images

notifications:
  email: false
