language: bash

services: docker

env:
  - VERSION=7.1

before_script:
  - cd "src/$VERSION"
  - IMAGE_NAME="php:${VERSION}"

script:
  - travis_retry docker build -t "$IMAGE_NAME" .

after_script:
  - docker images

# vim:set et ts=2 sw=2:
